### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by tomvanoppens**
first draft on article about CRL and OCSP in datapower

### CODE REVIEW

**Comment by tonyffrench** [comment]
I would recommend you remove the OCSP section and focus on the CRL topic. Ideally the post should have some sample source materials, so someone could setup and test and end 2 end scenario. For example: It would be interesting to see if DataPower for Docker could be combined with http://vaultproject.io and its ability to provide a PEM based CRL using the PKI backend.

**Comment by ozairs** [comment]
Its unclear on the flow. At the beginning we talk about how CRLs are defined in the CA certificate, but then we setup an CRL endpoint lookup using either HTTP or LDAP. 
When we want to use a CRL via val credentials, it does not reference the object created in the default domain - assume its a global setting but need more detail to understand.
Furthermore, instead of talking about the object properties, I would have a paragraph describing the purpose of the configuration and then a link to the docs for more information.

As @tonyffrench mentioned, a use case with diagram, including an example will really help demonstrate the use case.

**Comment by tomvanoppens** [comment]
@tonyffrench 
- CRLs aren't Docker specific
- Had a look at vaultproject
- - it seems they add in restrictions allowing you only a subset of x509. 
- - i can't find an audit trail or an endorsement of a org/person who is an authority in this field.
- source materials, I'll add some some sample material to build a CA and CRLs but this is pretty straight forward
@ozairs 
- will add some clarifying flows (or an attempt to :smile:  )
- valid point that you can't find the relation, but isn't really one. This is just the way how it was implemented. Will make an attempt to make it a little clearer though.

**Comment by tomvanoppens** [comment]
@ozairs @tonyffrench added some quick edits, is this something you're looking for. I'll refine it when i get word back

**Pull request merged**
